### PR TITLE
Convert glob-stream to proper readable stream

### PR DESCRIPTION
**Pull request by phated**
I think the implementation is pretty solid (except the few TODOs) but I really need some help with tests.  I'd love for someone to take a stab at them.

### CODE REVIEW

**Comment by phated** [comment]
Implementation as per https://github.com/isaacs/node-glob/issues/291

**Comment by kyleholzinger** [comment]
Hey man! Sorry for the late start, but just getting to writing some tests now. Is there any description of what `GlobStream`'s behavior should be? I'm pretty unfamiliar streams so not sure if that's innately obvious. I read over [isaacs/node-glob#291](https://github.com/isaacs/node-glob/issues/291) but that seemed more like a direct question more than a description of the overall behavior

Happy holidays!

**Comment by phated** [comment]
No worries and happy holidays.

The general description is that it should be a Readable stream (so nothing should be able to be pushed onto the stream, only read from it) that emits an object for each match.  The best way for testing streams seems to be something like https://github.com/gulpjs/vinyl-fs/blob/master/test/src.js#L154-L157

Feel free to ask any other questions you have on this thread and I'll try to answer the best I can.

**Comment by kyleholzinger** [comment]
Sounds awesome! Thanks for the explanation, that definitely helps. I'll hop right on 'em 🏃

**Comment by phated** [comment]
Assigned this to @contra incase he has time to make suggestions/help @kyleholzinger writing tests this week

**Comment by contra** [comment]
@kyleholzinger LMK if you need any assistance w/ this.

**Comment by kyleholzinger** [comment]
Will do, thanks @contra @phated ! Sorry, been traveling for the holidays so haven't had much time to work but will jump on this as soon as I can!

**Comment by phated** [comment]
Merged the tests from @kyleholzinger with a bit of cleanup and rebased against the `test-refactor` branch (that one should be merged in *way* before this).

There's still more tests to write to get the coverage back up to 100% and TODOs inline that need to be finished.  If anyone wants to jump on them, feel free.

**Comment by phated** [comment]
Pending tests running and #88 being reviewed, I think this is done.  I'm probably going to squash this to 1 commit and label it "Breaking"

**Comment by phated** [comment]
@shinnn would you be available to help review this? I remember you submitted a PR to make us Streams3 compliant in the past.

**Comment by phated** [comment]
Also added @contra and @terinjokes as reviewers.

**Comment by phated** [comment]
I guess it's time to merge this.  I was hoping for some more reviews but oh well.

**Pull request merged**
