### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by shinnn**
glob-stream becomes modern Stream3 implementation by this PR.

### CODE REVIEW

**Comment by phated** [comment]
Thanks.  I am trying to solve some other problems before bumping the dependencies.  Going to close this and do it once I land the other changes.

**Comment by shinnn** [comment]
OK. But please remember that [this commit](https://github.com/gulpjs/glob-stream/pull/80/commits/78667bc339a149e5d922121378749e2113823517) is essential to upgrade to Stream3.

Or, should I remove the last commit and rename this PR to "Pass data to the stream correctly"?

**Comment by phated** [comment]
TBH, this probably shouldn't even be using a Transform stream since it is using it like a readable.  I need to investigate more.

**Comment by phated** [comment]
@shinnn some initial work at https://github.com/gulpjs/glob-stream/commit/8260e0a2d84ee4f3d82fc38c8035e958c1a60899 but I'm waiting for some answers to questions from isaacs on node-glob and I need to refactor the tests because they expect an `end` event without being drained right now.

**Pull request closed without merging**
